### ISSUE TITLE
Setting mouse position to edge of screen not working properly with differently sized monitors

### ISSUE THREAD

**Issue by dxrcy** [reinhello/quick_mouse#6]
I am using a secondary monitor slightly larger than my laptop's screen, and when clicking `Shift+W` and `Shift+D`, the mouse only moves close to the edge of the screen (where it would be if the screen were smaller).
`Shift+A` and `Shift+S` work as intended, and so do all hotkeys on the primary monitor.
This is a great project, btw, it is nicer than my version I think :)

**Comment by reinacchi** [comment]
Thank you! I'm inspired by your incredible project, too. 

Could you provide a video capture of the demonstration? My laptop's screen is small and therefore, I'm unable to locate the exact issue from here.

**Comment by dxrcy** [comment]
I am unable to use my monitor currently, but I might be able to spoof it.
